### ISSUE TITLE
Thêm API cho phép nạp thẻ từ API (Dành cho nối API từ plugin khác hoặc dùng web)

### ISSUE THREAD

**Issue by TypicalShavonne** [minevn/dotman#10]

**Comment by amadeusmz** [comment]
Nhờ em mô tả thêm về từng loại API như: input, output, hành động cụ thể, use case để anh dễ hình dung nha

**Comment by TypicalShavonne** [comment]
API nạp thẻ cho người chơi: đầu vào seri, mã, nhà mạng, tên player
đầu ra là mã id xử lí thẻ, có thể là mã hash của seri+mã+nhà mạng


API nạp thẻ: đầu vào seri, mã, nhà mạng
đầu ra là mã id xử lí thẻ, có thể là mã hash của seri+mã+nhà mạng
Nên làm thêm cơ chế phát đi Event khi thẻ đã được nạp thành công, trong event sẽ chứa cả mã hash ở phần đầu ra bên trên

**Comment by amadeusmz** [comment]
Hi em, anh xin lỗi vì anh rep hơi lâu.

**Trường hợp nối plugin khác vào DotMan**: Em có thể xem qua source code của DotMam và xem có hàm nào không, ví dụ như hàm [LogDAO - lấy danh sách thẻ đang chờ theo UUID](https://github.com/minevn/dotman/blob/66d5070e7d54c352bdadca14e491b54cc571c51d/dotman-plugin/src/main/java/net/minevn/dotman/database/LogDAO.kt#L86-L109) (lấy object LogDAO từ hàm `LogDAO.getInstance()`)

**Trường hợp nối từ website vào DotMan**: Trường hợp này anh nghĩ chỉ có cách tương tác qua HTTP mà quá trình này khá vất vả. Em xem xét cho website dùng dung MySQL với DotMan, rồi khi nạp thì insert log vào table log của DotMan nha. Tuy nhiên sắp tới anh sẽ tìm cách tốt hơn, nhưng ưu tiên thấp nên em khoan kỳ vọng nhiều

**Về Event khi nạp thẻ thành công**: Cái này anh cũng sẽ bổ sung trong Update sau.
