### ISSUE TITLE
Tôi có thắc mắc lớn

### ISSUE THREAD

**Issue by MeoNguOfficial** [minevn/dotman#2]
Câu 1: Vậy nếu tôi cài plugin Thẻ Siêu Tốc với DotMan liệu có bị xung đột không? Tôi có thể chạy 2 plugin đó cùng một lúc được không?
Câu 2: Vậy làm cách nào để link vào tài khoản để nhận tiền k
![image](https://github.com/minevn/dotman/assets/135810477/e7e26143-1072-4e51-a46b-5ba6137127f2)
hi donate?

**Comment by amadeusmz** [comment]
@MeoNguOfficial 

1. Mình nghĩ là không có vấn đề gì nếu chạy cùng lúc DotMan với plugin TheSieuToc, tuy nhiên mình không khuyến khích việc chạy cùng lúc 2 plugin.
   - Nếu bạn thấy TheSieuToc có tính năng nào bạn cần mà DotMan chưa có, hãy cho mình biết.
2. Bạn đăng nhập vào web thesieutoc, vào link này lấy APIKey & APISecret điền vào file `/plugins/DotMan/providers/thesieutoc.yml` để liên kết nha

**Comment by MeoNguOfficial** [comment]
Nối tiếp câu 2: Thế mình lấy API key v1 hay v2 của Thẻ siêu tốc vậy ạ?

**Comment by amadeusmz** [comment]
@MeoNguOfficial 
Ở đây nhé bạn: https://thesieutoc.net/api/apiv1
