### ISSUE TITLE
Vẫn còn lỗi không hiện log point nhận được trong lịch sử nạp thẻ server

### ISSUE THREAD

**Issue by MeoNguOfficial** [minevn/dotman#23]
![image](https://github.com/minevn/dotman/assets/135810477/0e873d2c-d248-422b-a1a5-757d10f0d9cc)
Vẫn còn lỗi không hiện log point nhận được trong lịch sử nạp thẻ server, mong fix

**Comment by amadeusmz** [comment]
@MeoNguOfficial Các lịch sử nạp trước khi bạn nâng lên phiên bản 1.1 thì sẽ không thể hiển thị số point nhận được nha.

**Comment by amadeusmz** [comment]
@MeoNguOfficial Nếu lỗi vẫn còn thì bạn nhắn tin cho mình để được hỗ trợ nha. Mình xin phép đóng issue.
