### ISSUE TITLE
free - lệnh tra cứu mã giao dịch

### ISSUE THREAD

**Issue by amadeusmz** [minevn/dotman#47]
Mỗi giao dịch nạp thẻ cào hoặc ngân hàng sẽ có mã giao dịch như hình, và đã được lưu vào bảng log của dotman.

Làm thêm lệnh tra cứu mã giao dịch:
- Input: Mã giao dịch
- Output: Tên người nạp, số tiền nạp, số point nhận, thời gian

![Image](https://github.com/user-attachments/assets/5df7b8b8-1d49-4123-9ccf-b3a06d09bc88)

**Comment by minhh2792** [comment]
eta: 3 ngày
